# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('mob_no', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
    ]
